name: OIDC Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
   AWS_REGION: ap-south-1        # cluster ap-south-1 la irukku, us-west-2 illa
   CLUSTER: eks-cluster
   NS: demo

jobs:
  verify:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::268140506109:role/YOUR_ROLE_NAME
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS
        run: aws sts get-caller-identity

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          aws eks update-kubeconfig --name "$CLUSTER" --region "$AWS_REGION"

      - name: What am I allowed to do
        run: |
          kubectl auth whoami                    # k8s ku enna identity-a theriyum
          kubectl auth can-i --list -n "$NS"

      - name: Allowed - should pass
        run: kubectl get pods -n "$NS"